on:
  schedule:
    # every Monday
    - cron: '0 0 * * 1'
jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Configure Git for commits
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
    - name: Refresh Highway Code data
      run: |-
        python -m pip install --no-compile -r requirements.txt
        python main.py
    - name: Commit and push if it changed
      run: |-
        # git checkout -b
        # git add .
        # timestamp=$(date -u)
        # git commit -m "Code updated ${timestamp}" || exit 0
        # git push origin $(date +'%Y-%m-%d')
    - name: Open pull request, if applicable
      uses: peter-evans/create-pull-request@v3
      with:
        branch-suffix: timestamp
